backend:
  name: github
  repo: iaenblanco/propinvest-sitio
  app_id: Ov23liaGtBSCJFnDWv1R
  auth_type: pkce

media_folder: "src/admin/uploads"
public_folder: "/admin/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" } 